[workspace]
members = [".", "ytmimi--markdown-fmt"]

[package]
name = "fmtm"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
markdown-fmt = { version = "0.1", path = "ytmimi--markdown-fmt" }
